version: '3.7'
services:
  tests:
    build: ./tests
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'mijailr/github-deployment']
    volumes:
      - ".:/plugin:ro"